import { jsPDF } from 'jspdf';
import { TRUCKS } from '../data/trucks';
import { ClipboardList, Download, X } from 'lucide-react';
import './ReportModal.css';

export default function ReportModal({
  isOpen,
  onClose,
  items = [],
  truckKey = 'medium',
  utilization = 0
}) {
  if (!isOpen) return null;

  const truck = TRUCKS[truckKey];

  const generatePDF = () => {
    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.setTextColor(59, 130, 246);
    doc.text('SmartStack Cargo Packing Report', 20, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 28);

    doc.setFillColor(240, 240, 250);
    doc.roundedRect(15, 35, 180, 35, 3, 3, 'F');

    doc.setFontSize(11);
    doc.setTextColor(0);
    doc.text(`Truck Type: ${truck.name}`, 20, 45);
    doc.text(`Truck Dimensions: ${truck.w}×${truck.h}×${truck.d} cm`, 20, 52);
    doc.text(`Total Items Loaded: ${items.length}`, 110, 45);
    doc.text(`Space Utilization: ${utilization.toFixed(1)}%`, 110, 52);
    doc.text(`Total Weight: ${items.reduce((s, i) => s + (i.weight || 0), 0).toFixed(1)} kg`, 20, 59);

    let y = 80;
    doc.setFillColor(59, 130, 246);
    doc.setTextColor(255);
    doc.rect(15, y - 6, 180, 8, 'F');
    doc.setFontSize(9);
    doc.text('#', 18, y);
    doc.text('Type', 28, y);
    doc.text('Dimensions', 70, y);
    doc.text('Weight', 105, y);
    doc.text('Position', 130, y);
    doc.text('Stability', 170, y);

    doc.setTextColor(0);
    y += 8;

    items.forEach((item, i) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }

      if (i % 2 === 0) {
        doc.setFillColor(248, 248, 252);
        doc.rect(15, y - 5, 180, 7, 'F');
      }

      doc.setFontSize(8);
      doc.text(`${i + 1}`, 18, y);
      doc.text((item.name || '').substring(0, 12), 28, y);
      doc.text(`${item.l}×${item.w}×${item.h}`, 70, y);
      doc.text(`${(item.weight || 0).toFixed(1)} kg`, 105, y);
      doc.text(`(${(item.x || 0).toFixed(0)},${(item.y || 0).toFixed(0)},${(item.z || 0).toFixed(0)})`, 130, y);
      doc.text(`${((item.stability || 0) * 100).toFixed(0)}%`, 173, y);

      y += 7;
    });

    y = Math.max(y + 10, 250);
    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    doc.setDrawColor(200);
    doc.line(15, y, 195, y);
    y += 10;

    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text('This report was generated by SmartStack Pro AI Cargo Loading System.', 20, y);
    doc.text('All items have been optimally placed for maximum stability and space efficiency.', 20, y + 5);

    const filename = `SmartStack_Report_${new Date().toISOString().slice(0, 10)}.pdf`;
    doc.save(filename);
  };

  return (
    <div className="report-modal">
      <div className="report-content">
        <h2><ClipboardList size={22} /> Cargo Packing Report</h2>

        <div className="report-scrollable">
          <div className="report-header">
            <div className="report-stat">
              <label>Truck Type</label>
              <span className="value">{truck.name}</span>
            </div>
            <div className="report-stat">
              <label>Total Items</label>
              <span className="value">{items.length}</span>
            </div>
            <div className="report-stat">
              <label>Space Utilization</label>
              <span className="value">{utilization.toFixed(1)}%</span>
            </div>
            <div className="report-stat">
              <label>Report Date</label>
              <span className="value">{new Date().toLocaleString()}</span>
            </div>
          </div>

          <table className="report-table">
            <thead>
              <tr>
                <th>#</th>
                <th>Type</th>
                <th>Dimensions (L×W×H)</th>
                <th>Weight</th>
                <th>Position (X,Y,Z)</th>
                <th>Stability</th>
              </tr>
            </thead>
            <tbody>
              {items.map((item, i) => (
                <tr key={item.id ?? i}>
                  <td>{i + 1}</td>
                  <td>
                    <span className={`type-badge type-${item.type}`}>{item.name}</span>
                  </td>
                  <td>{item.l}×{item.w}×{item.h} cm</td>
                  <td>{(item.weight || 0).toFixed(1)} kg</td>
                  <td>({(item.x || 0).toFixed(0)}, {(item.y || 0).toFixed(0)}, {(item.z || 0).toFixed(0)})</td>
                  <td>{((item.stability || 0) * 100).toFixed(0)}%</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="report-actions">
          <button className="download-pdf" onClick={generatePDF}>
            <Download size={16} /> Download PDF Report
          </button>
          <button className="close-report" onClick={onClose}>
            <X size={16} /> Close
          </button>
        </div>
      </div>
    </div>
  );
}
